## Common Substrings
#### Given two strings, determine if they share a common substring. A substring may be as small as one character.
For example, the words "a", "and", "art" share the common substring . The words "be" and "cat" do not share a substring.

In [1]:
s1 = 'hello'
s2 = 'world'

In [4]:
len(set(s1).intersection(set(s2)))

2

## Common Child

In [98]:
import numpy as np

In [105]:
s1 = 'AA'
s2 = 'ABBA'

In [106]:
def child(s1, s2): 
    X = list(s1)
    Y = list(s2)
    # find the length of the strings 
    m = len(X) 
    n = len(Y) 
  
    # declaring the array for storing the dp values 
    L = [[None]*(n+1) for i in xrange(m+1)] 
  
    """Following steps build L[m+1][n+1] in bottom up fashion 
    Note: L[i][j] contains length of LCS of X[0..i-1] 
    and Y[0..j-1]"""
    for i in range(m+1): 
        for j in range(n+1): 
            if i == 0 or j == 0 : 
                L[i][j] = 0
            elif X[i-1] == Y[j-1]: 
                L[i][j] = L[i-1][j-1]+1
            else: 
                L[i][j] = max(L[i-1][j] , L[i][j-1]) 
  
    # L[m][n] contains the length of LCS of X[0..n-1] & Y[0..m-1] 
    print(np.array(L))
    return L[m][n] 
      

In [107]:
child(s1,s2)

[[0 0 0 0 0]
 [0 1 1 1 1]
 [0 1 1 1 2]]


2

In [64]:
m.

1

In [68]:
m[4+1:]

[]

In [33]:
set(list('da')).intersection(set(list('dma')))

{'a', 'd'}

In [16]:
m=[1,3]

In [17]:
t = [1,3]

In [18]:
m==t

True

In [3]:
[1,2] in m

False

In [32]:
s1_list = list(s1)
s2_list = list(s2)
for i in xrange(len(s1_list)):
    print(i)
    s1_list.pop(i)
    print(s1_list)
    for j in xrange(len(s2_list)):
        s2_list.pop(j)
        print(s2_list)
        if s2_list==s1_list:
            print('True')
        else:
            print('False')
        s2_list = list(s2)
    s1_list = list(s1)
    


0
['A', 'R', 'R', 'Y']
['A', 'L', 'L', 'Y']
False
['S', 'L', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'L']
False
1
['H', 'R', 'R', 'Y']
['A', 'L', 'L', 'Y']
False
['S', 'L', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'L']
False
2
['H', 'A', 'R', 'Y']
['A', 'L', 'L', 'Y']
False
['S', 'L', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'L']
False
3
['H', 'A', 'R', 'Y']
['A', 'L', 'L', 'Y']
False
['S', 'L', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'L']
False
4
['H', 'A', 'R', 'R']
['A', 'L', 'L', 'Y']
False
['S', 'L', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'Y']
False
['S', 'A', 'L', 'L']
False


In [9]:
list(s1)==list(s1)

True