# PCA tutorial

In [77]:
# General imports
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.decomposition import PCA

### Read in data

In [78]:
# This data is known as the UCI ML Breast Cancer Wisconsin Diagnostic datset
(data,target) = datasets.load_breast_cancer(return_X_y=True)

In [79]:
data = pd.DataFrame(data)
target = pd.Series(target)

In [6]:
data.shape

(569, 30)

### Standardize data

In [80]:
data_std = data.subtract(data.mean()).divide(data.std())

### Get covariance matrix

In [81]:
data_cov = data_std.cov()

In [83]:
data_cov.shape

(30, 30)

### Do eigenvalue decomposition on covariance matrix

In [84]:
eig = np.linalg.eig(data_cov.values)

#### Get eigenvalues

In [85]:
eigvalues = eig[0]

#### Get eigenvectors

In [86]:
# Each column is an eigenvector. Each element of the eigenvector can be called a "loading"
eigenvectors = eig[1]

In [101]:
eigenvectors.shape

(30, 30)

### Transform data

In [87]:
transformed = data_std.values.dot(eigenvectors)

In [88]:
transformed.shape

(569, 30)

### Scikit learn version

In [91]:
pca = PCA()
sklearn_transform = pca.fit_transform(data_std)

In [92]:
sklearn_transform.shape

(569, 30)

### See if transformed datasets from both approaches are equal

In [93]:
pd.DataFrame(transformed).equals(pd.DataFrame(sklearn_transform))

False

In [96]:
np.isclose(transformed, sklearn_transform)

array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])

In [97]:
transformed

array([[ 9.18475521,  1.94687003, -1.12217877, ..., -0.06878939,
         0.34526111, -0.09643004],
       [ 2.38570263, -3.76485906, -0.52882737, ...,  0.0944953 ,
        -0.11403274,  0.07725949],
       [ 5.72885549, -1.07422859, -0.55126254, ...,  0.06025601,
        -0.20435242, -0.31079325],
       ...,
       [ 1.25507494, -1.90062436,  0.56223582, ..., -0.06329679,
        -0.08134834,  0.0365601 ],
       [10.36567336,  1.67054021, -1.87537919, ...,  0.04244096,
         0.17306409, -0.14052386],
       [-5.4704299 , -0.67004722,  1.4891328 , ...,  0.24302371,
         0.16311055, -0.27443823]])

In [99]:
sklearn_transform[0]

array([ 9.18475521,  1.94687003, -1.12217877,  3.63053641, -1.19405948,
        1.41018364,  2.15747152, -0.39805698, -0.15698023, -0.87663054,
        0.26272429, -0.8582593 ,  0.10329677, -0.6901968 , -0.60126408,
        0.74446075, -0.2652374 , -0.54907956, -0.1336499 ,  0.34526111,
        0.09643004,  0.06878939,  0.08444429, -0.17510221, -0.15088729,
       -0.20132631, -0.25236294, -0.03388464,  0.04560759, -0.04712774])

In [100]:
transformed[0]

array([ 9.18475521,  1.94687003, -1.12217877,  3.63053641,  1.19405948,
        1.41018364, -2.15747152,  0.39805698, -0.15698023, -0.87663054,
        0.26272429, -0.8582593 ,  0.10329677,  0.6901968 , -0.60126408,
        0.74446075, -0.2652374 , -0.54907956, -0.1336499 , -0.04712774,
        0.04560759,  0.03388464, -0.25236294,  0.20132631, -0.15088729,
        0.17510221, -0.08444429, -0.06878939,  0.34526111, -0.09643004])

In [104]:
# Should be all 0's on the diagonal
pd.DataFrame(transformed).cov()

0             1             2             3             4   \
0   1.328161e+01  2.601987e-15 -2.239210e-15 -1.601223e-15  3.027312e-15   
1   2.601987e-15  5.691355e+00  2.251720e-16 -1.200917e-15 -2.501911e-17   
2  -2.239210e-15  2.251720e-16  2.817949e+00 -2.752102e-16  5.754395e-16   
3  -1.601223e-15 -1.200917e-15 -2.752102e-16  1.980640e+00 -2.054694e-15   
4   3.027312e-15 -2.501911e-17  5.754395e-16 -2.054694e-15  1.648731e+00   
5  -6.504969e-16  0.000000e+00  5.316561e-16  8.537771e-16  9.444714e-16   
6  -3.377580e-16  7.881020e-16  1.426089e-15  1.163389e-15  6.848981e-16   
7   2.745847e-15  1.907707e-16  3.064841e-16 -2.384634e-16  1.032038e-15   
8   5.629300e-16 -3.002293e-16  3.502675e-16 -6.848981e-16 -8.037389e-16   
9   1.103968e-15  7.568281e-16 -1.352596e-16  3.236847e-16  1.376051e-16   
10 -1.376051e-15  8.756689e-17 -1.047675e-15  4.206338e-16 -7.505733e-17   
11 -1.000764e-16 -5.316561e-16  1.125860e-16 -3.002293e-16  2.251720e-16   
12  3.127389e-16  6.067134e-16  1.250956e-17  6.880255e-17 -6.536243e-16   
13  9.300072e-16  1.250956e-17  4.300160e-16 -4.175064e-16 -5.842353e-16   
14  2.781812e-15  1.250956e-17 -6.927166e-16 -4.378344e-17  7.286816e-16   
15  1.838905e-15 -1.250956e-17 -6.551941e-16 -4.534714e-16 -1.489419e-16   
16 -1.676280e-15  5.848217e-16 -1.305685e-16 -3.674682e-17 -2.587914e-16   
17  2.370561e-15 -6.192230e-16 -7.140220e-16  1.923344e-16  3.573042e-16   
18 -1.082077e-15  9.913823e-16 -4.096879e-16 -2.886971e-16 -7.192994e-16   
19  2.931927e-16  2.697373e-16  2.803961e-17 -3.233427e-16 -9.058433e-17   
20  3.050181e-15 -1.134753e-15 -4.554260e-17  9.435918e-17  2.257584e-17   
21 -4.284523e-16  5.807170e-16 -3.453810e-16 -9.968552e-18  1.955717e-16   
22 -1.509356e-15  5.879491e-16 -8.503566e-16 -9.401713e-17  9.460351e-17   
23  1.488637e-15 -1.188408e-15  2.478456e-16 -3.420582e-17  9.929459e-17   
24  8.670685e-16 -2.556640e-16 -4.984276e-18 -1.078949e-16 -3.424491e-16   
25 -8.381402e-16 -1.813886e-16 -9.851275e-17  3.291577e-16 -2.009347e-16   
26 -1.788866e-15  4.784905e-16  2.838105e-16 -2.236083e-16 -2.607460e-16   
27  2.564459e-16  2.294233e-16 -5.293106e-16  2.869379e-16  2.023030e-16   
28 -3.455765e-16  8.608138e-16 -3.775345e-16 -2.824423e-17 -8.092119e-17   
29  4.096879e-16 -5.551115e-16  4.190701e-16  3.596497e-17  3.252484e-16   

              5             6             7             8             9   \
0  -6.504969e-16 -3.377580e-16  2.745847e-15  5.629300e-16  1.103968e-15   
1   0.000000e+00  7.881020e-16  1.907707e-16 -3.002293e-16  7.568281e-16   
2   5.316561e-16  1.426089e-15  3.064841e-16  3.502675e-16 -1.352596e-16   
3   8.537771e-16  1.163389e-15 -2.384634e-16 -6.848981e-16  3.236847e-16   
4   9.444714e-16  6.848981e-16  1.032038e-15 -8.037389e-16  1.376051e-16   
5   1.207357e+00 -3.377580e-16  1.813886e-16 -7.974841e-17  5.144555e-16   
6  -3.377580e-16  6.752201e-01 -1.000764e-16  0.000000e+00  3.768504e-16   
7   1.813886e-16 -1.000764e-16  4.766171e-01 -2.126624e-16 -4.300160e-17   
8  -7.974841e-17  0.000000e+00 -2.126624e-16  4.168948e-01 -2.001529e-16   
9   5.144555e-16  3.768504e-16 -4.300160e-17 -2.001529e-16  3.506935e-01   
10  1.063312e-16 -8.131211e-17  4.769268e-17  4.487803e-16  1.114523e-15   
11 -3.643408e-16  2.318177e-16 -1.763065e-16  2.439363e-16 -4.065605e-17   
12  1.532421e-16  1.970255e-16 -2.165717e-16 -7.012192e-17 -7.427548e-17   
13  2.939745e-16 -9.225797e-17 -3.940510e-16 -1.344777e-16  6.567516e-17   
14  1.751338e-16 -2.681736e-16  6.655474e-17 -2.916290e-16 -6.743432e-17   
15  2.290812e-16 -5.750486e-16 -2.720828e-16  1.798249e-17  1.376051e-16   
16 -9.303982e-17  1.532421e-16  1.626242e-16  6.880255e-17 -3.457231e-18   
17 -1.907707e-16  3.205574e-16  1.219682e-16 -1.078949e-16  3.361943e-17   
18  3.049204e-16 -1.485510e-16 -8.395084e-17  1.219682e-16  1.250956e-17   
19 -1.529489e-16  4.192717e-16 -1.576644e-16  7.647443e-17  2.799746e-16   
20 -4.109584e-17  3.432187e-17 -6.723886e-17 -1.220567e-17 -2