In [1]:
import pandas as pd
from sklearn.multiclass import OneVsRestClassifier
from sklearn.decomposition import PCA
import xgboost as xgb

In [2]:
train = pd.read_csv('train.csv',header=None)
test = pd.read_csv('test.csv',header=None)

In [3]:
# import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

/Users/matthew.goodwin/MyStuff/Education/DataScienceToolkit/DataScienceCode/ds_python_virtualenv/lib/python2.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [4]:
X = train.iloc[:,:294]
Y = train.iloc[:,294:]

In [10]:
pca = PCA(n_components=5)

In [11]:
x_new = pca.fit_transform(X)

In [12]:
x_new

array([[-1.06357511, -0.49261828, -0.0419664 , -0.42360994, -0.57327887],
       [-1.25953812, -0.08400864, -0.02193481,  0.0410204 , -0.32865315],
       [ 0.21740543, -0.62917119, -0.75935732, -0.04941241, -0.99589633],
       ...,
       [-0.95740738,  0.23272137,  0.13155411,  0.18148398,  0.88871637],
       [-0.24034179, -0.18718771,  0.30663042,  0.56476281,  1.27222919],
       [-1.94906743,  0.09771889, -0.2851477 ,  0.03312912,  0.88742291]])

In [13]:
classif = OneVsRestClassifier(xgb.XGBClassifier())
classif.fit(X, Y)

OneVsRestClassifier(estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1),
          n_jobs=1)

In [48]:
out = classif.predict(test)

In [49]:
out.sum(axis=1)[out.sum(axis=1)>1]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [21]:
clf = RandomForestClassifier(n_estimators=5)
clf = clf.fit(X, Y)

In [24]:
data = clf.predict(test)

In [27]:
data.sum(axis=1)[data.sum(axis=1)>1]

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [14]:
import tensorflow as tf
from tensorflow.keras import layers

In [32]:
model = tf.keras.Sequential()

In [33]:
model.add(layers.Dense(10, activation='relu'))
# Add another:
model.add(layers.Dense(10, activation='relu'))
# Add a softmax layer with 10 output units:
model.add(layers.Dense(6, activation='softmax'))

In [34]:
model.compile(optimizer=tf.train.AdamOptimizer(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [24]:
type(X.values)

numpy.ndarray

In [35]:
model.fit(X.values, Y.values, epochs=6, batch_size=32)

Epoch 1/6
1438/1438 [==============================] - 0s 159us/step - loss: 1.6276 - acc: 0.4465
Epoch 2/6
1438/1438 [==============================] - 0s 33us/step - loss: 1.1007 - acc: 0.6572
Epoch 3/6
1438/1438 [==============================] - 0s 33us/step - loss: 0.9054 - acc: 0.7142
Epoch 4/6
1438/1438 [==============================] - 0s 33us/step - loss: 0.8427 - acc: 0.7253
Epoch 5/6
1438/1438 [==============================] - 0s 32us/step - loss: 0.7989 - acc: 0.7434
Epoch 6/6
1438/1438 [==============================] - 0s 33us/step - loss: 0.7759 - acc: 0.7434


In [38]:
import heapq

In [39]:

model.predict(X.values)

array([[3.7648886e-02, 5.2877341e-04, 1.6420874e-03, 6.7383461e-02,
        4.4751263e-01, 4.4528422e-01],
       [9.2148870e-02, 1.3035425e-03, 1.2220809e-03, 2.5935933e-02,
        2.6495981e-01, 6.1442977e-01],
       [4.6423376e-02, 4.1738696e-02, 5.8349118e-02, 3.8468811e-01,
        1.8952420e-01, 2.7927652e-01],
       ...,
       [2.5209150e-01, 9.4133365e-04, 2.2253622e-03, 2.1543181e-04,
        2.4582730e-01, 4.9869907e-01],
       [5.3028798e-01, 5.7995645e-04, 2.5312679e-03, 4.4804276e-04,
        6.9181196e-02, 3.9697146e-01],
       [3.8290519e-01, 3.5128492e-04, 5.8816723e-04, 2.5515147e-03,
        1.5271683e-01, 4.6088710e-01]], dtype=float32)

In [52]:
# k-fold validation
for i in xrange(5,6):
    
#     classif = OneVsRestClassifier(xgb.XGBClassifier())
# classif.fit(X, Y)

    scores = cross_val_score(classif, X, Y, cv=10)
    print(scores)
    print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.54861111 0.45833333 0.38888889 0.45138889 0.26388889 0.54861111
 0.70833333 0.61805556 0.22377622 0.25174825]
Accuracy: 0.45 (+/- 0.31)


In [53]:
xgb.XGBClassifier?

In [17]:
train.head()

0         1         2         3         4         5         6    \
0  0.826575  0.843082  0.805944  0.785864  0.772749  0.854208  0.863394   
1  0.766867  0.669694  0.636238  0.612133  0.639010  0.603999  0.583958   
2  0.962784  0.975387  0.963950  0.955206  0.956827  0.971538  0.975437   
3  0.758844  0.772668  0.791800  0.827195  0.861022  0.755208  0.669177   
4  0.767603  0.875207  0.866511  0.874739  0.818681  0.826858  0.842438   

        7         8         9   ...        290       291       292       293  \
0  0.816732  0.829742  0.776793 ...   0.010687  0.010919  0.011375  0.015069   
1  0.775580  0.815867  0.676433 ...   0.050673  0.055661  0.079765  0.097522   
2  0.934207  0.858234  0.742964 ...   0.232948  0.195177  0.221791  0.201402   
3  0.754382  0.675287  0.773369 ...   0.297193  0.254088  0.221800  0.146297   
4  0.773873  0.877341  0.867682 ...   0.129825  0.075116  0.060953  0.022725   

   294  295  296  297  298  299  
0    0    0    0    1    0    1  
1    0    0    0    1    0    1  
2    0    0    0    1    0    1  
3    0    0    1    0    0    0  
4    0    0    1    0    0    0  

[5 rows x 300 columns]