In [44]:
import pandas as pd
from sklearn.multiclass import OneVsRestClassifier
from sklearn.decomposition import PCA
import xgboost as xgb

In [2]:
train = pd.read_csv('train.csv',header=None)
test = pd.read_csv('test.csv',header=None)

In [3]:
# import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

/Users/matthew.goodwin/MyStuff/Education/DataScienceToolkit/DataScienceCode/ds_python_virtualenv/lib/python2.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [4]:
X = train.iloc[:,:294]
Y = train.iloc[:,294:]

In [45]:
clf = xgb.XGBClassifier()
clf = clf.fit(X,Y)

ValueError: bad input shape (1438, 6)

In [31]:
pca = PCA(n_components=5)

In [35]:
x_new = pca.fit_transform(X)

In [36]:
x_new

array([[-1.0635751 , -0.49261819, -0.04195504, -0.42355669, -0.57310857],
       [-1.25953812, -0.08400858, -0.02192969,  0.04104335, -0.32859797],
       [ 0.21740543, -0.62917124, -0.75935929, -0.04940676, -0.99591983],
       ...,
       [-0.95740738,  0.23272143,  0.13155484,  0.18147769,  0.88869561],
       [-0.24034179, -0.18718771,  0.30662944,  0.56476151,  1.27219523],
       [-1.94906743,  0.09771889, -0.28514926,  0.03311883,  0.88737719]])

In [47]:
classif = OneVsRestClassifier(xgb.XGBClassifier())
classif.fit(X, Y)

OneVsRestClassifier(estimator=XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1),
          n_jobs=1)

In [48]:
out = classif.predict(test)

In [49]:
out.sum(axis=1)[out.sum(axis=1)>1]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [21]:
clf = RandomForestClassifier(n_estimators=5)
clf = clf.fit(X, Y)

In [24]:
data = clf.predict(test)

In [27]:
data.sum(axis=1)[data.sum(axis=1)>1]

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [23]:
pd.DataFrame(data).sum(axis=1)

0      1.0
1      0.0
2      1.0
3      1.0
4      1.0
5      1.0
6      1.0
7      1.0
8      0.0
9      1.0
10     1.0
11     1.0
12     2.0
13     0.0
14     1.0
15     1.0
16     1.0
17     1.0
18     0.0
19     0.0
20     1.0
21     1.0
22     1.0
23     1.0
24     0.0
25     1.0
26     1.0
27     2.0
28     1.0
29     1.0
      ... 
936    0.0
937    1.0
938    1.0
939    1.0
940    1.0
941    0.0
942    1.0
943    0.0
944    1.0
945    1.0
946    1.0
947    2.0
948    2.0
949    1.0
950    2.0
951    1.0
952    0.0
953    1.0
954    1.0
955    0.0
956    1.0
957    1.0
958    1.0
959    1.0
960    1.0
961    1.0
962    0.0
963    0.0
964    1.0
965    0.0
Length: 966, dtype: float64

In [52]:
# k-fold validation
for i in xrange(5,6):
    
    classif = OneVsRestClassifier(xgb.XGBClassifier())
# classif.fit(X, Y)

    scores = cross_val_score(classif, X, Y, cv=10)
    print(scores)
    print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

[0.54861111 0.45833333 0.38888889 0.45138889 0.26388889 0.54861111
 0.70833333 0.61805556 0.22377622 0.25174825]
Accuracy: 0.45 (+/- 0.31)


In [53]:
xgb.XGBClassifier?

In [17]:
train.head()

0         1         2         3         4         5         6    \
0  0.826575  0.843082  0.805944  0.785864  0.772749  0.854208  0.863394   
1  0.766867  0.669694  0.636238  0.612133  0.639010  0.603999  0.583958   
2  0.962784  0.975387  0.963950  0.955206  0.956827  0.971538  0.975437   
3  0.758844  0.772668  0.791800  0.827195  0.861022  0.755208  0.669177   
4  0.767603  0.875207  0.866511  0.874739  0.818681  0.826858  0.842438   

        7         8         9   ...        290       291       292       293  \
0  0.816732  0.829742  0.776793 ...   0.010687  0.010919  0.011375  0.015069   
1  0.775580  0.815867  0.676433 ...   0.050673  0.055661  0.079765  0.097522   
2  0.934207  0.858234  0.742964 ...   0.232948  0.195177  0.221791  0.201402   
3  0.754382  0.675287  0.773369 ...   0.297193  0.254088  0.221800  0.146297   
4  0.773873  0.877341  0.867682 ...   0.129825  0.075116  0.060953  0.022725   

   294  295  296  297  298  299  
0    0    0    0    1    0    1  
1    0    0    0    1    0    1  
2    0    0    0    1    0    1  
3    0    0    1    0    0    0  
4    0    0    1    0    0    0  

[5 rows x 300 columns]

In [41]:
Y

294  295  296  297  298  299
0       0    0    0    1    0    1
1       0    0    0    1    0    1
2       0    0    0    1    0    1
3       0    0    1    0    0    0
4       0    0    1    0    0    0
5       0    0    1    0    0    0
6       0    0    1    0    0    0
7       0    0    1    0    0    0
8       0    0    1    0    0    0
9       0    0    1    0    0    0
10      0    0    1    0    0    0
11      0    0    1    0    0    0
12      0    0    1    0    0    0
13      0    0    1    0    0    0
14      0    0    1    0    0    0
15      0    0    1    0    0    0
16      0    0    1    0    0    0
17      0    0    1    0    0    0
18      0    0    1    0    0    0
19      0    0    1    0    0    0
20      0    0    1    0    0    0
21      0    0    1    0    0    0
22      0    0    1    0    0    0
23      0    0    1    0    0    0
24      0    0    1    0    0    0
25      0    0    1    0    0    0
26      0    0    1    0    0    0
27      0    0    1    0    0    0
28      0    0    1    0    0    0
29      0    0    1    0    0    0
...   ...  ...  ...  ...  ...  ...
1408    0    0    1    1    0    0
1409    0    0    1    1    0    0
1410    0    0    1    1    0    0
1411    0    0    1    1    0    0
1412    0    0    1    1    0    0
1413    0    0    1    1    0    0
1414    0    0    1    1    0    0
1415    0    0    1    1    0    0
1416    0    0    1    1    0    0
1417    0    0    1    1    0    0
1418    0    0    1    1    0    0
1419    0    0    1    1    0    0
1420    0    0    1    0    1    0
1421    0    0    1    0    1    0
1422    0    0    1    0    1    0
1423    0    0    1    0    1    0
1424    0    0    1    0    1    0
1425    0    0    1    0    1    0
1426    0    0    1    0    1    0
1427    1    0    0    0    0    1
1428    1    0    0    0    0    1
1429    1    0    0    0    0    1
1430    1    0    0    0    0    1
1431    1    0    0    0    0    1
1432    1    0    0    0    0    1
1433    1    0    0    0    0    1
1434    1    0    0    0    0    1
1435    1    0    0    0    0    1
1436    1    0    0    0    0    1
1437    1    0    0    0    0    1

[1438 rows x 6 columns]